version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - echo "Install phase"

  pre_build:
    commands:
      - echo "Installing frontend dependencies"
      - cd frontend
      - npm ci
      - cd ../backend
      - chmod +x gradlew

  build:
    commands:
      - echo "Building frontend"
      - cd ../frontend
      - npm run build
      - echo "Building backend"
      - cd ../backend
      - ./gradlew clean build -x test

  post_build:
    commands:
      - echo "Build completed. 프론트엔드 빌드 결과물(dist)만 S3 루트 경로로 강제 배포합니다!"
      - aws s3 sync ../frontend/dist s3://user34-prod-website --delete

artifacts:
  files:
    - backend/build/libs/*.jar
  discard-paths: no