version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20

  pre_build:
    commands:
      - cd frontend && npm ci

  build:
    commands:
      - cd frontend && npm run build
      - cd ../backend && chmod +x gradlew
      - cd ../backend && ./gradlew clean build -x test

artifacts:
  files:
    - backend/build/libs/*.jar
    - frontend/dist/**/*