version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - npm --prefix frontend install

  build:
    commands:
      - npx --prefix frontend ng test --no-watch --no-progress --browsers=ChromeHeadlessCI